-
  name: install apache httpd service
  hosts: all
  tasks:
    - name: code to install apache2
      yum:
        name: httpd
        state: present
    
    - debug:
        msg: Apache successfully installed

    - name: code to start the apache2 service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        
    - name: stop firewalld.service
      service:
        name: firewalld.service
        state: stopped

    - name: code to create directory
      file:
        path: /opt/log
        state: directory

    - name: code to create file apache-log.logs
      file: 
        path: /opt/log/apache-log.logs
        state: touch
    
    - name: write message ino that file
      lineinfile: 
        path: /opt/log/apache-log.logs
        line: 'apache is successfully installed'
