-
  name: varible sample
  hosts: prasad
  vars: 
    a: 10
    b: 20.50
    c: 'MH14GS0371'
    d: "i love my india"
  tasks: 
    - name: code to create dir
      file: 
        path: /opt/variable
        state: directory
    
    - name: code to create file into dir
      file:
        path: /opt/variable/concetp.txt
        state: touch
    
    - name: code to tex into file
      lineinfile:
        path: /opt/variable/concetp.txt
        state: present
        line: 'the value of a is {{a}} and value of b is {{b}} and value of c is {{c}} and value of d is {{d}}'