-
  name: code for loop
  hosts: prasad
  tasks:
    - name: below code for yum installation using loop 
      yum:
        name: "{{ item }}"
        state: present
      with_item:
      - git
      - docker
      - net-tools
      