-
  name: code for loop
  hosts: prasad
  tasks:
    - name: below code for yum installation using loop 
      yum:
        name: "{{ item }}"
        state: present
      loop:
       - git
       - docker
       - net-tools
      