-
  name: code for loop
  hosts: prasad
  tasks:
   - name: code to install loop 
     yum:
       name: "{{ item }}"
       state: present
     with_item:
     - git
     - docker
     - net-tools
      